---
# This playbook converts Docker to go from loopback devices to direct LVM.
# It's assumed a separate volume has been created for each instance and attached
# as /dev/vdb device.
# Run this playbook once OpenShift has been deployed. Beware, Docker is
# installed on each node as a dependency of the OpenShift packages.
# Warning! We delete /var/lib/docker in this playbook.

- name: Configure Docker Storage
  hosts: nodes
  user: centos
  sudo: yes
  connection: ssh
  gather_facts: no

  tasks:

  - name: Determine if Docker uses loopback devices
    shell: docker info | grep 'Data file:.*loop'
    register: loop_device_check
    ignore_errors: True
    failed_when: False
    changed_when: False

  - name: Check if /dev/vdb exists
    command: test -e /dev/vdb
    register: vdb_check
    when: loop_device_check.rc == 0
    ignore_errors: True
    failed_when: False
    changed_when: False

  - include: docker_storage.yml
    when: loop_device_check.rc == 0 and vdb_check.rc == 0
