---
# This playbook converts Docker to go from loopback devices to direct LVM.
# It's assumed a separate volume has been created for each instance and attached
# as /dev/vdb device.
# Run this playbook once OpenShift has been deployed. Beware, Docker is
# installed on each node as a dependency of the OpenShift packages.
# Warning! We delete /var/lib/docker in this playbook.

- name: Configure Docker Storage
  hosts: all
  user: centos
  sudo: yes
  connection: ssh
  gather_facts: no

  tasks:

  - name: Determine if Docker uses loopback devices
    shell: docker info | grep 'Data file:.*loop'
    register: loop_device_check
    ignore_errors: yes

  - debug:
      var: loop_device_check

  - name: Fail if loopback devices are not detected
    fail:
      msg: Docker don't use loopback devices.
    when: loop_device_check.rc == 1

  - name: Check if /dev/vdb exists
    command: test -e /dev/vdb
    register: vdb_check
    ignore_errors: yes

  - debug:
      var: vdb_check

  - name: Fail if /dev/vdb doesn't exist
    fail:
      msg: /dev/vdb doesn't exist.
    when: vdb_check.rc == 1

  - name: Start lvm2-lvmetad
    service:
      name: lvm2-lvmetad
      state: started
      enabled: yes

  - name: Stop Docker
    service:
      name: docker
      state: stopped
      enabled: no

  - name: Delete /var/lib/docker
    command: rm -rf /var/lib/docker

  - name: Copy the docker-storage-setup config file
    copy:
      src: docker-storage-setup
      dest: /etc/sysconfig/docker-storage-setup
      owner: root
      group: root
      mode: 0644

  - name: Run docker-storage-setup
    command: /bin/docker-storage-setup
    register: setup_output

  - debug:
      var: setup_output

  - name: Start Docker
    service:
      name: docker
      state: started
      enabled: yes
